---
  - name: "Deploy jar file"
    hosts: GoldenWasteWebApp

    tasks:
    - name: Copy the file from master to GoldenWasteWebApp
      copy: src="/var/lib/jenkins/jobs/goldenwaste-sda-hackathon/builds/1/archive/target/goldenWastedd-0.0.1-SNAPSHOT.jar" dest="/home/ubuntu/ROOT.jar"

    - name: Run JAR file
      shell: java -jar /home/ubuntu/ROOT.jar
      
    - name: Wait for WebApp to start
      wait_for: port=8080 timeout=60