---
  - name: "Install Jenkins Docker in localhost"
    hosts: localhost
    gather_facts: false
    connection: local
    tasks:

      - name: Install Maven
        become: yes
        apt:
          name: maven
          state: present
          update_cache: yes

      - name: Install apache2
        apt:
          name: apache2
          update_cache: yes
          state: latest

      - name: Install JDK
        apt:
          name: default-jdk
          update_cache: yes
          state: latest

      - name: Add Jenkins apt key
        shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -

      - name: Add debian package to sources list 
        shell: 'sh -c "echo deb https://pkg.jenkins.io/debian binary/ > /etc/apt/sources.list.d/jenkins.list"'

      - name: Install Jenkins
        apt:
          name: jenkins
          update_cache: yes
          state: latest

      - name: Get the initial admin password
        shell: cat /var/lib/jenkins/secrets/initialAdminPassword
        register: getresult

      - local_action: command echo item
        with_items: var=getresult.stdout_lines

      - name: Add debian package to sources list 
        shell: usermod -a -G root jenkins

      - name: Restart service jenkins, in all cases
        service:
          name: jenkins
          state: restarted

      - name: Install Docker
        apt:
          name: docker.io
          update_cache: yes
          state: latest