---
  - name: Run Jenkins
    hosts: localhost
    become: yes
    gather_facts: false
    connection: local
    tasks:
      - name: Running Jenkins docker image
        shell: docker run -d -p 50000:50000 -p 8080:8080 --restart=on-failure --name jenkins jenkins/jenkins:lts-jdk11

      - name: Get the initial admin password
        shell: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
        register: getresult

      - name: Install Artifact Deployer Jenkins Plugin
        shell: docker exec jenkins jenkins-plugin-cli --plugins artifactdeployer:1.2

      - name: Restart Jenkins docker image
        shell: docker restart jenkins

      - debug:
          msg="{{ getresult.msg }}"
        when: getresult.changed