---
  - name: Run SonarQube
    hosts: localhost
    become: yes
    gather_facts: false
    connection: local
    tasks:
      - name: Create sonarqube_data volume
        shell: docker volume create --name sonarqube_data

      - name: Create sonarqube_logs volume
        shell: docker volume create --name sonarqube_logs

      - name: Create sonarqube_extensions volume
        shell: docker volume create --name sonarqube_extensions

      - name: Run SonarQube docker image
        shell: docker run --rm -p 9000:9000 -v sonarqube_extensions:/opt/sonarqube/extensions -d --name sonarqube sonarqube:community